[build]
  command = "npm run build:frontend"
  publish = "dist/public"
  functions = "netlify-functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
